[build]
  command = "BASE_PATH=/dradental npm run build && mkdir -p public && cp -R dist/* public/"
  publish = "public"

[[redirects]]
  from = "/"
  to = "/ro"
  status = 301
  force = true

[[redirects]]
  from = "/dradental/*"
  to = "/:splat"
  status = 200