[build]
  publish = "public"
  command = """
    cd public/dradental && 
    npm run build && 
    cp -R dist/* ../../public/
  """

[[redirects]]
  from = "/"
  to = "/ro"
  status = 301
  force = true