[build]
  publish = "public"
  command = """
    cd public/dradental && 
    BASE_PATH=/dradental npm run build && 
    mkdir -p ../dradental && 
    cp -R dist/* ../dradental/
  """

[[redirects]]
  from = "/"
  to = "/ro"
  status = 301
  force = true

[[redirects]]
  from = "/dradental/*"
  to = "/:splat"
  status = 200